### PR TITLE
CONTRIBUTING.md: Rules for approving pull requests

### PR DESCRIPTION
**Pull request by nottrobin**
Define the threshold for and practice around approving a pull request.

### CODE REVIEW

**Review by deadlight — APPROVED** [review]
:+1:

**Comment by nottrobin** [comment]
Hmm doesn't look like I can reset the base to ubuntudesign/master. :(. Closing.

**Review by anthonydillon — COMMENTED** [review]
I don't think we need to move too quickly on these reviews. I would like to say at least 2 +1's and have the PR up for more than 24 hours so everyone gets a chance to review.

**Comment by deadlight** [comment]
@anthonydillon I think that it would be better to get them closed relatively quickly and have any changes issued as PRs. Especially useful for times like right now where I have more changes waiting on a PR approval.

**Comment by anthonydillon** [comment]
But we will miss people opinions and once it lands becomes approved and may be difficult to change with another PR.

**Comment by nottrobin** [comment]
Move here: https://github.com/ubuntudesign/webteam-practices/pull/13

**Pull request closed without merging**
